### ISSUE TITLE
Update to Angular 8 failed on migration

### ISSUE THREAD

**Issue by florian-kittel** [jodit/jodit-angular#33]
Hi,

the migration of my Angular application to version 8 failed. I got the following message:
```
The template migration strategy uses the Angular compiler internally and therefore projects that no longer build successfully after the update
cannot use the template migration strategy. Please ensure there are no AOT compilation errors.
            
Could not setup migration strategy for "projects/editor/tsconfig.app.json". The following error has been reported:
            
Error: error TS100: jodit-angular\jodit-angular.ts(6,2): Error during template compile of 'JoditAngularModule' Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule' 'NgModule' calls 'ɵmakeDecorator'.

Migration can be rerun with: "ng update @angular/core --from 7 --to 8 --migrate-only"
```

**Comment by vasudevpareek07** [comment]
@florian-kittel, I am also getting the same error after upgrading angular version from 7 to 8. In Angular 7, it was working fine. Did you find out the solution?

**Comment by florian-kittel** [comment]
@vasudevpareek07 Sorry, but I also didn't find a solution. So we are not using jodit anymore. At the moment we havn't any good and lightweight replacement.

**Comment by MrElectroNick** [comment]
Hi @florian-kittel @vasudevpareek07 all current versions of Angular are supported. Please check readme
